version: '3'
services:
  test-backend:
    container_name: test-backend
    depends_on:
      - db_test
    build:
      context: ./back-end
      dockerfile: Dockerfile.test.yml
    environment:
      # These are stored in the .env file
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_PORT: "${MYSQL_PORT}"
      NODE_ENV: debug
      TESTING: 1
      WAIT_HOSTS: "db_test:${MYSQL_PORT}"
      APISUFFIX: '${APISUFFIX}'
    ports:
      - '9000:9000'
    networks:
      - test-backend-c4

  db_test:
    container_name: db_test
    image: mariadb:10.4.7
    restart: always
    logging:
      driver: none
    volumes:
      - db_data_test:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d/
    environment:
      # These are stored in the .env file
      DB_HOST: db_test
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_PORT: "${MYSQL_PORT}"
      MYSQL_INITDB_SKIP_TZINFO: 1
    ports:
      - "3308:${MYSQL_PORT}"
    networks:
      - test-backend-c4
    command: mysqld --innodb-buffer-pool-size=256M
volumes:
  db_data_test: {}
networks:
  test-backend-c4:
