version: '3'
services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: DockerFile
    depends_on:
      - db
    restart: always
    environment:
      # These are stored in the .env file
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_PORT: '${MYSQL_PORT}'
      PROD_URL: '${PROD_URL}'
      PROD_PORT: '${PROD_PORT}'
      JWTSECRET: '${JWTSECRET}'
      APISUFFIX: '${APISUFFIX}'
      NODE_ENV: production
    ports:
      - '9000:9000'
    networks:
      - c4
  db:
    image: mariadb:10.4
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      # These are stored in the .env file
      DB_HOST: db
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_PORT: '${MYSQL_PORT}'
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    networks:
      - c4
    command: mysqld --innodb-buffer-pool-size=256M
networks:
  c4:
    driver: bridge
