version: '3'
services:
  unit-back-end:
    container_name: unit-back-end
    depends_on:
      - db
    build:
      context: ./back-end
      dockerfile: Dockerfile-unittest.yml
    volumes:
      - './back-end:/back-end/'
      - /back-end/node_modules
    environment:
      # These are stored in the .env file
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_PORT: "${MYSQL_PORT}"
      TESTING: 1
      WAIT_HOSTS: db:${MYSQL_PORT}
    ports:
      - '9000:3000'
    networks:
      - unit-c4
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d/
    logging:
      driver: none
    environment:
      # These are stored in the .env file
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_PORT: "${MYSQL_PORT}"
    ports:
      - '3308:${MYSQL_PORT}'
    networks:
      - unit-c4
networks:
  unit-c4:
volumes:
  db_data: {}
